pipeline_name: "Dynamic_VSR_Upscale_Test"

pipeline:
  - class: "upscale.dynamic_upscale_node.DynamicUpscaleNode"
    params:
      model_filename: "RealESRGAN_x4plus.pth"
      scale: 4
      threshold: 0.02
      tile_size: 64
      padding: 16
      refresh_interval: 60
      batch_size: 12
      fp16: true
