pipeline_name: "Dynamic_Upscale_SPAN"

pipeline:
  - class: "upscale.dynamic_upscale_node.DynamicUpscaleNode"
    params:
      model_filename: "spanx4_ch48.pth"
      model_type: "span"
      scale: 4
      feature_channels: 48
      threshold: 0.01
      tile_size: 64
      padding: 16
      refresh_interval: 60
      batch_size: 16
      fp16: true
      debug_view: true

