from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


class ImageOutputFormat(str, Enum):
    SAME_AS_INPUT = "same_as_input"
    PNG = "png"
    JPG = "jpg"
    JPEG = "jpeg"
    WEBP = "webp"


class ImageProcessRequest(BaseModel):
    """
    Request schema for processing a single image.

    Preferred modern usage:
        pipeline_id + overrides

    Backward-compatible usage:
        pipeline_config_path
    """

    input_path: str = Field(
        ...,
        description="Absolute OS path to the input image",
        json_schema_extra={"example": "C:/App/data/input/image.png"},
    )

    output_path: Optional[str] = Field(
        None,
        description="Absolute OS path to save the processed image. If omitted, the service generates one.",
        json_schema_extra={"example": "C:/App/data/output/image_processed.png"},
    )

    pipeline_id: Optional[str] = Field(
        None,
        description="UI-friendly pipeline ID, e.g. '03_old_video_enhancement'",
        json_schema_extra={"example": "03_old_video_enhancement"},
    )

    pipeline_config_path: Optional[str] = Field(
        None,
        description="Backward-compatible absolute OS path to the YAML pipeline configuration file",
        json_schema_extra={"example": "C:/App/configs/pipeline_configs/test_upscale.yaml"},
    )

    overrides: Dict[str, Any] = Field(
        default_factory=dict,
        description="Runtime pipeline parameter overrides generated by UI controls",
        json_schema_extra={
            "example": {
                "prompt": "person",
                "blur_intensity": 41,
                "preserve_mask": False,
            }
        },
    )

    output_format: ImageOutputFormat = Field(
        default=ImageOutputFormat.SAME_AS_INPUT,
        description="Requested output image format",
    )

    preserve_metadata: bool = Field(
        default=False,
        description="Whether to preserve image metadata when possible",
    )

    @field_validator("input_path")
    @classmethod
    def validate_input_path(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError("input_path cannot be empty")

        return value

    @field_validator("output_path")
    @classmethod
    def validate_output_path(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None

        value = value.strip()
        return value or None

    @field_validator("pipeline_id", "pipeline_config_path")
    @classmethod
    def normalize_optional_string(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None

        value = value.strip()
        return value or None

    def get_pipeline_reference(self) -> str:
        """
        Returns the preferred pipeline reference.

        Services can call this so they work with either:
        - pipeline_id
        - pipeline_config_path
        """
        if self.pipeline_id:
            return self.pipeline_id

        if self.pipeline_config_path:
            return self.pipeline_config_path

        raise ValueError("Either pipeline_id or pipeline_config_path must be provided.")


class ImageBatchProcessRequest(BaseModel):
    """
    Request schema for processing a directory of images.

    Preferred modern usage:
        pipeline_id + overrides

    Backward-compatible usage:
        pipeline_config_path
    """

    input_dir: str = Field(
        ...,
        description="Absolute OS path to the directory containing input images",
        json_schema_extra={"example": "C:/App/data/input/images"},
    )

    output_dir: Optional[str] = Field(
        None,
        description="Absolute OS path to the directory where processed images will be saved. If omitted, service generates one.",
        json_schema_extra={"example": "C:/App/data/output/images"},
    )

    pipeline_id: Optional[str] = Field(
        None,
        description="UI-friendly pipeline ID, e.g. '03_old_video_enhancement'",
        json_schema_extra={"example": "03_old_video_enhancement"},
    )

    pipeline_config_path: Optional[str] = Field(
        None,
        description="Backward-compatible absolute OS path to the YAML pipeline configuration file",
        json_schema_extra={"example": "C:/App/configs/pipeline_configs/test_upscale.yaml"},
    )

    overrides: Dict[str, Any] = Field(
        default_factory=dict,
        description="Runtime pipeline parameter overrides generated by UI controls",
    )

    output_format: ImageOutputFormat = Field(
        default=ImageOutputFormat.SAME_AS_INPUT,
        description="Requested output image format",
    )

    recursive: bool = Field(
        default=False,
        description="Whether to process nested subdirectories",
    )

    preserve_filenames: bool = Field(
        default=True,
        description="Whether processed outputs should keep the original filenames",
    )

    supported_extensions: List[str] = Field(
        default_factory=lambda: [".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".webp"],
        description="Allowed image extensions for batch processing",
    )

    @field_validator("input_dir")
    @classmethod
    def validate_input_dir(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError("input_dir cannot be empty")

        return value

    @field_validator("output_dir")
    @classmethod
    def validate_output_dir(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None

        value = value.strip()
        return value or None

    @field_validator("pipeline_id", "pipeline_config_path")
    @classmethod
    def normalize_optional_string(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None

        value = value.strip()
        return value or None

    @field_validator("supported_extensions")
    @classmethod
    def normalize_supported_extensions(cls, values: List[str]) -> List[str]:
        normalized = []

        for ext in values:
            ext = ext.lower().strip()

            if not ext:
                continue

            if not ext.startswith("."):
                ext = f".{ext}"

            normalized.append(ext)

        return sorted(set(normalized))

    def get_pipeline_reference(self) -> str:
        """
        Returns the preferred pipeline reference.

        Services can call this so they work with either:
        - pipeline_id
        - pipeline_config_path
        """
        if self.pipeline_id:
            return self.pipeline_id

        if self.pipeline_config_path:
            return self.pipeline_config_path

        raise ValueError("Either pipeline_id or pipeline_config_path must be provided.")


class ImageProcessResult(BaseModel):
    """
    Metadata for a completed single-image job.
    """

    job_id: str
    input_path: str
    output_path: str

    pipeline_id: Optional[str] = None
    pipeline_config_path: Optional[str] = None

    width: Optional[int] = Field(None, ge=1)
    height: Optional[int] = Field(None, ge=1)

    output_format: ImageOutputFormat = ImageOutputFormat.SAME_AS_INPUT

    output_url: Optional[str] = Field(
        None,
        description="URL used by UI to preview/download the result",
    )


class ImageBatchProcessResult(BaseModel):
    """
    Metadata for a completed image-batch job.
    """

    job_id: str
    input_dir: str
    output_dir: str

    pipeline_id: Optional[str] = None
    pipeline_config_path: Optional[str] = None

    total_images: int = Field(0, ge=0)
    processed_images: int = Field(0, ge=0)
    failed_images: int = Field(0, ge=0)

    output_urls: List[str] = Field(
        default_factory=list,
        description="Optional URLs for processed images",
    )