from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field, field_validator


class VideoOutputFormat(str, Enum):
    MP4 = "mp4"
    MOV = "mov"
    WEBM = "webm"
    MKV = "mkv"
    SAME_AS_INPUT = "same_as_input"


class VideoProcessRequest(BaseModel):
    """
    Request schema for processing a single video.

    Preferred modern usage:
        pipeline_id + overrides

    Backward-compatible usage:
        pipeline_config_path
    """

    input_path: str = Field(
        ...,
        description="Absolute OS path to the input video file",
        json_schema_extra={"example": "C:/App/data/input/video.mp4"},
    )

    output_path: Optional[str] = Field(
        None,
        description="Absolute OS path to save the processed video. If omitted, the service generates one.",
        json_schema_extra={"example": "C:/App/data/output/video_processed.mp4"},
    )

    pipeline_id: Optional[str] = Field(
        None,
        description="UI-friendly pipeline ID, e.g. '01_cinematic_prompt_blur'",
        json_schema_extra={"example": "01_cinematic_prompt_blur"},
    )

    pipeline_config_path: Optional[str] = Field(
        None,
        description="Backward-compatible absolute OS path to the YAML pipeline configuration file",
        json_schema_extra={"example": "C:/App/configs/pipeline_configs/test_colorization.yaml"},
    )

    overrides: Dict[str, Any] = Field(
        default_factory=dict,
        description="Runtime pipeline parameter overrides generated by UI controls",
        json_schema_extra={
            "example": {
                "prompt": "person",
                "blur_intensity": 41,
                "detect_every_n_frames": 3,
            }
        },
    )

    output_format: VideoOutputFormat = Field(
        default=VideoOutputFormat.MP4,
        description="Requested output video container/format",
    )

    keep_original_audio: bool = Field(
        default=True,
        description="Whether to mux original audio back into the processed video when possible",
    )

    max_ai_resolution: Optional[int] = Field(
        default=1920,
        ge=256,
        le=4096,
        description="Maximum input dimension used for AI processing. Larger videos are downscaled before processing.",
    )

    generate_preview: bool = Field(
        default=True,
        description="Whether to generate a UI-friendly preview URL/result when possible",
    )

    @field_validator("input_path")
    @classmethod
    def validate_input_path(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError("input_path cannot be empty")

        return value

    @field_validator("output_path")
    @classmethod
    def validate_output_path(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None

        value = value.strip()
        return value or None

    @field_validator("pipeline_id", "pipeline_config_path")
    @classmethod
    def normalize_optional_string(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None

        value = value.strip()
        return value or None

    def get_pipeline_reference(self) -> str:
        """
        Returns the preferred pipeline reference.

        Services can call this so they work with either:
        - pipeline_id
        - pipeline_config_path
        """
        if self.pipeline_id:
            return self.pipeline_id

        if self.pipeline_config_path:
            return self.pipeline_config_path

        raise ValueError("Either pipeline_id or pipeline_config_path must be provided.")


class VideoProcessResult(BaseModel):
    """
    Metadata for a completed video processing job.
    """

    job_id: str

    input_path: str
    output_path: str

    pipeline_id: Optional[str] = None
    pipeline_config_path: Optional[str] = None

    output_format: VideoOutputFormat = VideoOutputFormat.MP4

    width: Optional[int] = Field(None, ge=1)
    height: Optional[int] = Field(None, ge=1)
    fps: Optional[float] = Field(None, gt=0)
    duration_seconds: Optional[float] = Field(None, ge=0)

    frame_count: Optional[int] = Field(None, ge=0)

    has_audio: Optional[bool] = Field(
        None,
        description="Whether the output video contains audio",
    )

    output_url: Optional[str] = Field(
        None,
        description="URL used by UI to preview/download the result",
    )

    preview_url: Optional[str] = Field(
        None,
        description="Optional lightweight preview URL",
    )